"""Build a new editable map from the shared primitive manifest. Run inside Unreal."""
import json
import math
from pathlib import Path
from datetime import datetime
import unreal

ROOT = Path(__file__).resolve().parent
scene = json.loads((ROOT / 'scene.json').read_text())
geometry = json.loads((ROOT / 'geometry.json').read_text())
asset_root = '/Game/WalkthroughStudio/' + datetime.now().strftime('%Y%m%d_%H%M%S_%f')
editor = unreal.get_editor_subsystem(unreal.LevelEditorSubsystem)
actors = unreal.get_editor_subsystem(unreal.EditorActorSubsystem)
assets = unreal.AssetToolsHelpers.get_asset_tools()
if not editor.new_level(asset_root + '/Home'):
    raise RuntimeError('Could not create a new map. Existing maps were not overwritten.')
meshes = {kind: unreal.load_asset('/Engine/BasicShapes/' + name) for kind, name in [('box', 'Cube'), ('sphere', 'Sphere'), ('cylinder', 'Cylinder')]}
materials = {}
elements = {e['id']: e for e in scene['elements']}
# OBJ meshes are generated by the same shape function as the browser renderer.
if (ROOT / 'meshes.json').exists():
    tasks = []
    for item in json.loads((ROOT / 'meshes.json').read_text()):
        task = unreal.AssetImportTask()
        task.filename = str(ROOT / item['file'])
        task.destination_path = asset_root + '/Meshes'
        task.destination_name = item['name']
        task.automated = True
        task.save = True
        opts = unreal.FbxImportUI()
        opts.import_mesh = True
        opts.import_materials = False
        opts.import_textures = False
        opts.mesh_type_to_import = unreal.FBXImportType.FBXIT_STATIC_MESH
        opts.static_mesh_import_data.combine_meshes = True
        opts.static_mesh_import_data.auto_generate_collision = False
        opts.static_mesh_import_data.convert_scene = False
        opts.static_mesh_import_data.normal_import_method = unreal.FBXNormalImportMethod.FBXNIM_IMPORT_NORMALS
        task.options = opts
        tasks.append((item['name'], task))
    assets.import_asset_tasks([task for _, task in tasks])
    for name, task in tasks:
        mesh = next((obj for obj in task.get_objects() if isinstance(obj, unreal.StaticMesh)), None)
        if mesh is None:
            raise RuntimeError('Could not import ' + name)
        meshes[name] = mesh

def family(item):
    if item['kind'] == 'cushion':
        return 'cloth'
    e = elements[item['element']]
    name = e['id']
    if name.startswith('roof-solar-panel-'):
        return 'solar'
    if name.startswith('roof-'):
        return 'roof'
    if item['kind'] in ['hedge', 'canopy']:
        return 'foliage'
    if name.startswith('mirror-face-'):
        return 'mirror'
    if '-botanical-' in name:
        return 'botanical'
    if e['kind'] in ['sofa', 'bed', 'rug'] or name.startswith(('duvet-', 'pillow-', 'throw-', 'curtain-', 'towel-', 'headboard-', 'bed-base-', 'round-rug-')):
        return 'cloth'
    if e['kind'] == 'floor' and e['room'] not in ['hall', 'laundry', 'bath1', 'bath2'] and not name.startswith(('context-', 'garden-')):
        return 'wood'
    if name.startswith(('deck-board-', 'deck-rail-')) or e['kind'] in ['chair', 'table']:
        return 'wood'
    if name.startswith(('tile-wall-', 'tile-')):
        return 'tile'
    if name.startswith(('tap-', 'basin-tap-', 'shower-', 'coffee-leg-', 'fridge-')):
        return 'metal'
    return 'plain'


def material(color, glass=False, surface="plain"):
    key = color + ("glass" if glass else surface)
    if key in materials:
        return materials[key]
    mat = assets.create_asset('M_' + key.replace('#', ''), asset_root + '/Materials', unreal.Material, unreal.MaterialFactoryNew())
    expr = unreal.MaterialEditingLibrary.create_material_expression(mat, unreal.MaterialExpressionConstant3Vector)
    rgb = [int(color[i:i+2], 16) / 255 for i in (1, 3, 5)]
    rgb = [v / 12.92 if v <= .04045 else ((v + .055) / 1.055) ** 2.4 for v in rgb]
    expr.set_editor_property('constant', unreal.LinearColor(*rgb, 1))
    if surface in ['wood', 'cloth', 'botanical', 'foliage', 'tile']:
        mat.set_editor_property('two_sided', surface == 'foliage')
        world = unreal.MaterialEditingLibrary.create_material_expression(mat, unreal.MaterialExpressionWorldPosition)
        node = unreal.MaterialEditingLibrary.create_material_expression(mat, unreal.MaterialExpressionCustom)
        pins = []
        for pin in ['P', 'C']:
            inp = unreal.CustomInput()
            inp.set_editor_property('input_name', pin)
            pins.append(inp)
        node.set_editor_property('inputs', pins)
        node.set_editor_property('output_type', unreal.CustomMaterialOutputType.CMOT_FLOAT3)
        noise = 'float n=frac(sin(dot(floor(P*2.5),float3(127.1,311.7,74.7)))*43758.5453);'
        code = noise + 'return C*(.85+.2*n);'
        if surface == 'wood':
            code = noise + 'float2 q=frac(P.xy/float2(14,210)); float edge=min(min(q.x,1-q.x),min(q.y,1-q.y));float grain=sin(P.x*7+sin(P.y*.04)*2)*.025; return C*(.9+.09*n+grain)*lerp(.65,1,smoothstep(.002,.014,edge));'
        if surface == 'foliage':
            code = noise + 'return C*(.6+.65*n);'
        if surface == 'tile':
            code = 'float3 q=frac(P/32);float3 e=min(q,1-q);float edge=min(e.x,min(e.y,e.z));return C*lerp(.73,1,smoothstep(.002,.012,edge));'
        if surface == 'botanical':
            code = 'float2 cell=floor(P.xy/12),q=frac(P.xy/12)-.5;float seed=frac(sin(dot(cell,float2(127.1,311.7)))*43758.5453),a=seed*6.283;q=mul(float2x2(cos(a),-sin(a),sin(a),cos(a)),q);float r=length(q),petal=.21+.075*cos(6*atan2(q.y,q.x));float flower=1-smoothstep(petal-.012,petal+.012,r);float3 ink=lerp(float3(.12,.22,.24),float3(.62,.69,.64),step(.48,seed));float3 col=lerp(C*.94,ink,flower*.85);return lerp(col,float3(.18,.24,.22),1-smoothstep(.028,.055,r));'
        node.set_editor_property('code', code)
        unreal.MaterialEditingLibrary.connect_material_expressions(world, '', node, 'P')
        unreal.MaterialEditingLibrary.connect_material_expressions(expr, '', node, 'C')
        expr = node
    unreal.MaterialEditingLibrary.connect_material_property(expr, '', unreal.MaterialProperty.MP_BASE_COLOR)
    rough = unreal.MaterialEditingLibrary.create_material_expression(mat, unreal.MaterialExpressionConstant)
    rough.set_editor_property('r', .2 if glass else {'wood': .5, 'cloth': .93, 'botanical': .93, 'mirror': .035, 'metal': .26, 'foliage': .88, 'roof': .48, 'solar': .3}.get(surface,.78))
    unreal.MaterialEditingLibrary.connect_material_property(rough, '', unreal.MaterialProperty.MP_ROUGHNESS)
    if surface in ['roof', 'solar', 'mirror']:
        metal = unreal.MaterialEditingLibrary.create_material_expression(mat, unreal.MaterialExpressionConstant)
        metal.set_editor_property('r', 1.0 if surface == 'mirror' else .18)
        unreal.MaterialEditingLibrary.connect_material_property(metal, '', unreal.MaterialProperty.MP_METALLIC)
    if glass:
        mat.set_editor_property('blend_mode', unreal.BlendMode.BLEND_TRANSLUCENT)
        opacity = unreal.MaterialEditingLibrary.create_material_expression(mat, unreal.MaterialExpressionConstant)
        opacity.set_editor_property('r', .15)
        unreal.MaterialEditingLibrary.connect_material_property(opacity, '', unreal.MaterialProperty.MP_OPACITY)
    unreal.MaterialEditingLibrary.recompile_material(mat)
    unreal.EditorAssetLibrary.save_loaded_asset(mat)
    materials[key] = mat
    return mat

for item in geometry:
    x, y, z = item['position']
    sx, sy, sz = item['size']
    actor = actors.spawn_actor_from_class(unreal.StaticMeshActor, unreal.Vector(x*100, z*100, y*100), unreal.Rotator(pitch=0, yaw=-item['rotation'], roll=0))
    actor.set_actor_label(item['id'])
    actor.set_folder_path(item['room'])
    component = actor.static_mesh_component
    component.set_static_mesh(meshes[item.get('mesh', item['kind'])])
    component.set_material(0, material(item['color'], item['glass'], family(item)))
    component.set_editor_property('cast_shadow', not item['glass'])
    if 'mesh' not in item:
        actor.set_actor_scale3d(unreal.Vector(sx, sz, sy))

for i, point in enumerate(scene['route']):
    x, y, z = point['position']; tx, ty, tz = point['target']
    pos, target = unreal.Vector(x*100, z*100, y*100), unreal.Vector(tx*100, tz*100, ty*100)
    camera = actors.spawn_actor_from_class(unreal.CineCameraActor, pos, unreal.MathLibrary.find_look_at_rotation(pos, target))
    camera.set_actor_label('Route_%03d_%s' % (i, point['room']))
    camera.get_cine_camera_component().set_editor_property('current_focal_length', 20)

# Bake the same eased route used in the browser, with a single continuous camera.
fps = 30
total_frames = math.ceil(sum(p['seconds'] for p in scene['route']) * fps)
sequence = assets.create_asset('HomeTour', asset_root, unreal.LevelSequence, unreal.LevelSequenceFactoryNew())
sequence.set_display_rate(unreal.FrameRate(fps, 1))
sequence.set_playback_start(0)
sequence.set_playback_end(total_frames)
first = scene['route'][0]
initial_position = unreal.Vector(first['position'][0] * 100, first['position'][2] * 100, first['position'][1] * 100)
initial_target = unreal.Vector(first['target'][0] * 100, first['target'][2] * 100, first['target'][1] * 100)
camera = actors.spawn_actor_from_class(unreal.CineCameraActor, initial_position, unreal.MathLibrary.find_look_at_rotation(initial_position, initial_target))
component = camera.get_cine_camera_component()
filmback = component.get_editor_property('filmback')
filmback.sensor_width, filmback.sensor_height = 36, 20.25
component.set_editor_property('filmback', filmback)
lens = component.get_editor_property('lens_settings')
lens.min_focal_length = 8
component.set_editor_property('lens_settings', lens)
component.set_editor_property('current_focal_length', 20.25 / (2 * math.tan(math.radians(34))))
focus = component.get_editor_property('focus_settings')
focus.focus_method = unreal.CameraFocusMethod.DISABLE
component.set_editor_property('focus_settings', focus)
binding = sequence.add_spawnable_from_instance(camera)
binding.set_name('Continuous home tour')
actors.destroy_actor(camera)
section = binding.add_track(unreal.MovieScene3DTransformTrack).add_section()
section.set_range(0, total_frames)
channels = section.get_all_channels()
previous_yaw = None
for frame in range(total_frames + 1):
    time, elapsed = frame / fps, 0
    for i, end in enumerate(scene['route']):
        start = scene['route'][max(0, i - 1)]
        if time <= elapsed + end['seconds'] or i == len(scene['route']) - 1:
            t = max(0, min(1, (time - elapsed) / end['seconds']))
            t = t * t * (3 - 2 * t)
            xyz = [a + (b - a) * t for a, b in zip(start['position'], end['position'])]
            aim = [a + (b - a) * t for a, b in zip(start['target'], end['target'])]
            break
        elapsed += end['seconds']
    pos = unreal.Vector(xyz[0]*100, xyz[2]*100, xyz[1]*100)
    target = unreal.Vector(aim[0]*100, aim[2]*100, aim[1]*100)
    rotation = unreal.MathLibrary.find_look_at_rotation(pos, target)
    yaw = rotation.yaw
    if previous_yaw is not None:
        yaw = previous_yaw + (yaw - previous_yaw + 180) % 360 - 180
    previous_yaw = yaw
    values = [pos.x, pos.y, pos.z, rotation.roll, rotation.pitch, yaw, 1, 1, 1]
    for k, value in enumerate(values):
        if frame == 0:
            channels[k].set_default(value)
        if k < 6:
            channels[k].add_key(unreal.FrameNumber(frame), value, interpolation=unreal.MovieSceneKeyInterpolation.LINEAR)
cut = sequence.add_track(unreal.MovieSceneCameraCutTrack).add_section()
cut.set_range(0, total_frames)
cut.set_camera_binding_id(sequence.get_binding_id(binding))
unreal.EditorAssetLibrary.save_loaded_asset(sequence)
config = assets.create_asset('Render4K', asset_root, unreal.MoviePipelinePrimaryConfig, unreal.MoviePipelinePrimaryConfigFactory())
output = config.find_or_add_setting_by_class(unreal.MoviePipelineOutputSetting)
output.output_resolution = unreal.IntPoint(3840, 2160)
output.output_directory = unreal.DirectoryPath(str(ROOT / 'Results' / asset_root.rsplit('/', 1)[-1]))
output.file_name_format = 'frame_{frame_number}'
output.zero_pad_frame_numbers = 6
output.use_custom_frame_rate = True
output.output_frame_rate = unreal.FrameRate(fps, 1)
output.override_existing_output = False
config.find_or_add_setting_by_class(unreal.MoviePipelineDeferredPassBase)
config.find_or_add_setting_by_class(unreal.MoviePipelineImageSequenceOutput_PNG)
aa = config.find_or_add_setting_by_class(unreal.MoviePipelineAntiAliasingSetting)
aa.spatial_sample_count = 4
aa.temporal_sample_count = 1
aa.engine_warm_up_count = 32
unreal.EditorAssetLibrary.save_loaded_asset(config)

sun = actors.spawn_actor_from_class(unreal.DirectionalLight, unreal.Vector(0, 0, 900), unreal.Rotator(pitch=-42, yaw=-115, roll=0))
sun.set_actor_label('Daylight')
sun.light_component.set_editor_property('intensity', 30000)
sun.light_component.set_editor_property('atmosphere_sun_light', True)
sun.light_component.set_editor_property('light_source_angle', 2.0)
sky = actors.spawn_actor_from_class(unreal.SkyLight, unreal.Vector(0, 0, 500))
sky.light_component.set_editor_property('intensity', 1.2)
sky.light_component.set_editor_property('real_time_capture', True)
actors.spawn_actor_from_class(unreal.SkyAtmosphere, unreal.Vector(0, 0, 0))
actors.spawn_actor_from_class(unreal.PlayerStart, unreal.Vector(*[v*100 for v in [scene['route'][0]['position'][0], scene['route'][0]['position'][2], scene['route'][0]['position'][1]]]))
pp = actors.spawn_actor_from_class(unreal.PostProcessVolume, unreal.Vector())
pp.set_editor_property('unbound', True)
settings = pp.get_editor_property('settings')
for key, value in {'override_auto_exposure_method': True, 'auto_exposure_method': unreal.AutoExposureMethod.AEM_MANUAL, 'override_auto_exposure_bias': True, 'auto_exposure_bias': -10.0, 'override_auto_exposure_apply_physical_camera_exposure': True, 'auto_exposure_apply_physical_camera_exposure': False, 'override_motion_blur_amount': True, 'motion_blur_amount': 0.0, 'override_lumen_scene_lighting_quality': True, 'lumen_scene_lighting_quality': 4.0, 'override_lumen_final_gather_quality': True, 'lumen_final_gather_quality': 4.0}.items():
    settings.set_editor_property(key, value)
pp.set_editor_property('settings', settings)
# Broad window daylight supplements the real sky during the comparison study.
for room in scene['rooms']:
    panes = [e for e in scene['elements'] if e['room'] == room['id'] and e['kind'] == 'window' and not e['id'].startswith('shower-')]
    for pane in panes:
        x,y,z = pane['position']
        rx,rz,rw,rd = room['bounds']
        pos = unreal.Vector(x*100,z*100,y*100)
        aim = unreal.Vector((rx+rw/2)*100,(rz+rd/2)*100,y*100)
        light = actors.spawn_actor_from_class(unreal.RectLight,pos,unreal.MathLibrary.find_look_at_rotation(pos,aim))
        light.set_actor_label('Window daylight ' + room['id'])
        light.light_component.set_editor_property('intensity', 6500.0)
        light.light_component.set_editor_property('source_width', max(pane['size'][0],pane['size'][2])*100)
        light.light_component.set_editor_property('source_height',pane['size'][1]*100)
        light.light_component.set_editor_property('attenuation_radius',650.0)
editor.save_current_level()
(ROOT / 'build-report.json').write_text(json.dumps({'map': asset_root + '/Home', 'sequence': sequence.get_path_name(), 'renderConfig': config.get_path_name(), 'primitives': len(geometry), 'frames': total_frames, 'fps': fps, 'rendered': False}, indent=2))
unreal.log('STUDIO_BUILD_OK: Walkthrough Studio saved ' + asset_root + '/Home. Draft geometry requires visual review.')
